version: '3'
services:
    database: 
        image: "postgres"
        ports:
            - "5432:5432"
        env_file:
            - "postgresql.env"
        volumes:
            - dbdata:/var/lib/postgresql/data/
volumes:
    dbdata: